---
title: "Longitudinal HW7"
author: "Mairead Dillon"
date: '2023-04-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load libraries
library(tidyverse)
library(readxl)
library(broom)
library(moments)

# Important data
data <- read_xls("/Users/maireaddillon/Documents/Duke/BIOS-718/Longitudinal-Analysis/HW7/LargePubHlthDataset.xls")
```
     
# Physical Activity
```{r}
# All
data %>% summarise(sample = length(na.omit(kcal)),
                   mean = mean(kcal, na.rm=T),
                   variance = var(kcal, na.rm=T),
                   skewness = skewness(kcal, na.rm=T),
                   kurtosis = kurtosis(kcal, na.rm=T))

# By age group
data %>% group_by(agegrp) %>% 
  summarise(sample = length(na.omit(kcal)),
            mean = mean(kcal, na.rm=T),
            variance = var(kcal, na.rm=T),
            skewness = skewness(kcal, na.rm=T),
            kurtosis = kurtosis(kcal, na.rm=T))

# Relative N
length(na.omit(data$kcal[data$agegrp==0])) / length(na.omit(data$kcal[data$agegrp==1]))

# Relative variance
var(na.omit(data$kcal[data$agegrp==0])) / var(na.omit(data$kcal[data$agegrp==1]))

# By sex
data %>% group_by(female) %>% 
  summarise(sample = length(na.omit(kcal)),
            mean = mean(kcal, na.rm=T),
            variance = var(kcal, na.rm=T),
            skewness = skewness(kcal, na.rm=T),
            kurtosis = kurtosis(kcal, na.rm=T))

# Relative N
length(na.omit(data$kcal[data$female==1])) / length(na.omit(data$kcal[data$female==0]))

# Relative variance
var(na.omit(data$kcal[data$female==1])) / var(na.omit(data$kcal[data$female==0]))

# Histogram
jpeg("/Users/maireaddillon/Documents/Duke/BIOS-718/Longitudinal-Analysis/HW7/physical_activity.jpg", quality = 100)
hist(data$kcal,
     main = "Physical Activity",
     xlab = "Physical Activity")
dev.off()
```
     
# Alcohol Consumption
```{r}
# All
data %>% summarise(sample = length(na.omit(alcoh)),
                   mean = mean(alcoh, na.rm=T),
                   variance = var(alcoh, na.rm=T),
                   skewness = skewness(alcoh, na.rm=T),
                   kurtosis = kurtosis(alcoh, na.rm=T))

# By age group
data %>% group_by(agegrp) %>% 
  summarise(sample = length(na.omit(alcoh)),
            mean = mean(alcoh, na.rm=T),
            variance = var(alcoh, na.rm=T),
            skewness = skewness(alcoh, na.rm=T),
            kurtosis = kurtosis(alcoh, na.rm=T))

# Relative N
length(na.omit(data$alcoh[data$agegrp==0])) / length(na.omit(data$alcoh[data$agegrp==1]))

# Relative variance
var(na.omit(data$alcoh[data$agegrp==0])) / var(na.omit(data$alcoh[data$agegrp==1]))

# By smoking status
data %>% group_by(cursmk) %>% 
  summarise(sample = length(na.omit(alcoh)),
            mean = mean(alcoh, na.rm=T),
            variance = var(alcoh, na.rm=T),
            skewness = skewness(alcoh, na.rm=T),
            kurtosis = kurtosis(alcoh, na.rm=T))

# Relative N
length(na.omit(data$alcoh[data$cursmk==1])) / length(na.omit(data$alcoh[data$cursmk==0]))

# Relative variance
var(na.omit(data$alcoh[data$cursmk==1])) / var(na.omit(data$alcoh[data$cursmk==0]))

# Histogram
jpeg("/Users/maireaddillon/Documents/Duke/BIOS-718/Longitudinal-Analysis/HW7/alcohol_consumption.jpg", quality = 100)
hist(data$alcoh,
     main = "Alcohol Consumption",
     xlab = "Alcohol Consumption")
dev.off()
```
        
# Systolic Blood Pressure
```{r}
# All
data %>% summarise(sample = length(na.omit(sysbp)),
                   mean = mean(sysbp, na.rm=T),
                   variance = var(sysbp, na.rm=T),
                   skewness = skewness(sysbp, na.rm=T),
                   kurtosis = kurtosis(sysbp, na.rm=T))

# By age group
data %>% group_by(agegrp) %>% 
  summarise(sample = length(na.omit(sysbp)),
            mean = mean(sysbp, na.rm=T),
            variance = var(sysbp, na.rm=T),
            skewness = skewness(sysbp, na.rm=T),
            kurtosis = kurtosis(sysbp, na.rm=T))

# Relative N
length(na.omit(data$sysbp[data$agegrp==0])) / length(na.omit(data$sysbp[data$agegrp==1]))

# Relative variance
var(na.omit(data$sysbp[data$agegrp==0])) / var(na.omit(data$sysbp[data$agegrp==1]))

# By sex
data %>% group_by(female) %>% 
  summarise(sample = length(na.omit(sysbp)),
            mean = mean(sysbp, na.rm=T),
            variance = var(sysbp, na.rm=T),
            skewness = skewness(sysbp, na.rm=T),
            kurtosis = kurtosis(sysbp, na.rm=T))

# Relative N
length(na.omit(data$sysbp[data$female==1])) / length(na.omit(data$sysbp[data$female==0]))

# Relative variance
var(na.omit(data$sysbp[data$female==1])) / var(na.omit(data$sysbp[data$female==0]))

# Histogram
jpeg("/Users/maireaddillon/Documents/Duke/BIOS-718/Longitudinal-Analysis/HW7/SBP.jpg", quality = 100)
hist(data$sysbp,
     main = "Systolic Blood Pressure",
     xlab = "Systolic Blood Pressure")
dev.off()
```
      
# C-Reactive Protein
```{r}
# All
data %>% summarise(sample = length(na.omit(crp)),
                   median = median(crp, na.rm=T),
                   iqr = IQR(crp, na.rm=T),
                   skewness = skewness(crp, na.rm=T),
                   kurtosis = kurtosis(crp, na.rm=T))

# By sex
data %>% group_by(female) %>%
  summarise(sample = length(na.omit(crp)),
            median = median(crp, na.rm=T),
            iqr = IQR(crp, na.rm=T),
            skewness = skewness(crp, na.rm=T),
            kurtosis = kurtosis(crp, na.rm=T))

# Relative N
length(na.omit(data$crp[data$female==1])) / length(na.omit(data$crp[data$female==0]))

# Relative variance
var(na.omit(data$crp[data$female==1])) / var(na.omit(data$crp[data$female==0]))

# Histogram
jpeg("/Users/maireaddillon/Documents/Duke/BIOS-718/Longitudinal-Analysis/HW7/CRP.jpg", quality = 100)
hist(data$crp,
     main = "C-Reactive Protein",
     xlab = "C-Reactive Protein")
dev.off()
```

        
# Stroke
```{r}
# All
data %>% summarise(sample = length(na.omit(stroke)),
                   mean = mean(stroke, na.rm=T),
                   variance = var(stroke, na.rm=T),
                   skewness = skewness(stroke, na.rm=T),
                   kurtosis = kurtosis(stroke, na.rm=T))

# By smoking status
data %>% group_by(cursmk) %>% 
  summarise(sample = length(na.omit(stroke)),
            mean = mean(stroke, na.rm=T),
            variance = var(stroke, na.rm=T),
            skewness = skewness(stroke, na.rm=T),
            kurtosis = kurtosis(stroke, na.rm=T))

# Relative N
length(na.omit(data$stroke[data$cursmk==1])) / length(na.omit(data$stroke[data$cursmk==0]))

# Relative variance
var(na.omit(data$stroke[data$cursmk==1])) / var(na.omit(data$stroke[data$cursmk==0]))

# By sex
data %>% group_by(female) %>% 
  summarise(sample = length(na.omit(stroke)),
            mean = mean(stroke, na.rm=T),
            variance = var(stroke, na.rm=T),
            skewness = skewness(stroke, na.rm=T),
            kurtosis = kurtosis(stroke, na.rm=T))

# Relative N
length(na.omit(data$stroke[data$female==1])) / length(na.omit(data$stroke[data$female==0]))

# Relative variance
var(na.omit(data$stroke[data$female==1])) / var(na.omit(data$stroke[data$female==0]))

# Histogram
jpeg("/Users/maireaddillon/Documents/Duke/BIOS-718/Longitudinal-Analysis/HW7/stroke.jpg", quality = 100)
hist(data$stroke,
     main = "Stroke",
     xlab = "Stroke")
dev.off()
```
      
## Simulations    
```{r}
# We use complete records; 135 incomplete records deleted.
HwkPop <- HwkPop[complete.cases(HwkPop),]
```
     
# Physical activity by age group
```{r}
# Set seed
set.seed(100)

# N = 100
B = 100

## Step 1: Compute population parameter for true difference between means:
#
# Population-level mean difference, PopDiff
PopDiff <-  -diff(t.test(kcal ~ agegrp, data=HwkPop)$estimate )

## Step 2: Generate random samples of size N for your Monte Carlo simulation
#          Place random samples in a list of data frames (make's life easier):

N <- seq(100, 500, by=50)
for (i in 1:length(N)) {
  
data_list <- map(.x = 1:B, .f = ~ sample_n(HwkPop, N[i]))
head(data_list[[1]])

## Step: 3: Collect your MC estimates and safe them in tmpout.
#           In this illustration, We've saved:
#           dif  = estimated mean difference: mean(Y[X==0]) - mean(Y[X==1])
#           lcl  = lower 95% conf. inv. estimate
#           ucl  = upper 95% conf. inv. estimate
#           cov  = decision of whether the CI contains the true difference
#           TrueDif = Population mean difference 

tmpout <- NULL
for(i in 1:B) {
#  tmpout <- rbind(tmpout, ( prod( t.test( kcal ~  female, data=data_list[[i]])$conf.int - TrueDif) < 0 )  )
  tst <- t.test(kcal ~ agegrp, data=data_list[[i]])
  dif <- -diff(tst$estimate)
  lcl <- tst$conf.int[1]
  ucl <- tst$conf.int[2]
  cov <- ( lcl <= PopDiff & PopDiff <= ucl )
  stat <- c(TrueDif = PopDiff, dif = dif, lcl = lcl, ucl=ucl, Cover = cov ) 
  tmpout <- rbind(tmpout, stat  )
}
head(tmpout)
print(apply(tmpout, 2, mean))

}
```
```{r}
# Set seed
set.seed(100)

# N = 100
B = 10000

## Step 1: Compute population parameter for true difference between means:
#
# Population-level mean difference, PopDiff
PopDiff <-  -diff(t.test(kcal ~ agegrp, data=HwkPop)$estimate )

## Step 2: Generate random samples of size N for your Monte Carlo simulation
#          Place random samples in a list of data frames (make's life easier):

N <- seq(350, 400, by=10)
for (i in 1:length(N)) {
  
data_list <- map(.x = 1:B, .f = ~ sample_n(HwkPop, N[i]))
head(data_list[[1]])

## Step: 3: Collect your MC estimates and safe them in tmpout.
#           In this illustration, We've saved:
#           dif  = estimated mean difference: mean(Y[X==0]) - mean(Y[X==1])
#           lcl  = lower 95% conf. inv. estimate
#           ucl  = upper 95% conf. inv. estimate
#           cov  = decision of whether the CI contains the true difference
#           TrueDif = Population mean difference 

tmpout <- NULL
for(i in 1:B) {
#  tmpout <- rbind(tmpout, ( prod( t.test( kcal ~  female, data=data_list[[i]])$conf.int - TrueDif) < 0 )  )
  tst <- t.test(kcal ~ agegrp, data=data_list[[i]])
  dif <- -diff(tst$estimate)
  lcl <- tst$conf.int[1]
  ucl <- tst$conf.int[2]
  cov <- ( lcl <= PopDiff & PopDiff <= ucl )
  stat <- c(TrueDif = PopDiff, dif = dif, lcl = lcl, ucl=ucl, Cover = cov ) 
  tmpout <- rbind(tmpout, stat  )
}
head(tmpout)
print(apply(tmpout, 2, mean))

}
```

     
# Physical activity by sex
```{r}
# Set seed
set.seed(100)

# N = 100
B = 100

## Step 1: Compute population parameter for true difference between means:
#
# Population-level mean difference, PopDiff
PopDiff <-  -diff(t.test(kcal ~ female, data=HwkPop)$estimate )

## Step 2: Generate random samples of size N for your Monte Carlo simulation
#          Place random samples in a list of data frames (make's life easier):

N <- seq(50, 100, by=10)
for (i in 1:length(N)) {
  
data_list <- map(.x = 1:B, .f = ~ sample_n(HwkPop, N[i]))
head(data_list[[1]])

## Step: 3: Collect your MC estimates and safe them in tmpout.
#           In this illustration, We've saved:
#           dif  = estimated mean difference: mean(Y[X==0]) - mean(Y[X==1])
#           lcl  = lower 95% conf. inv. estimate
#           ucl  = upper 95% conf. inv. estimate
#           cov  = decision of whether the CI contains the true difference
#           TrueDif = Population mean difference 

tmpout <- NULL
for(i in 1:B) {
#  tmpout <- rbind(tmpout, ( prod( t.test( kcal ~  female, data=data_list[[i]])$conf.int - TrueDif) < 0 )  )
  tst <- t.test( kcal ~  female, data=data_list[[i]])
  dif <- -diff(tst$estimate)
  lcl <- tst$conf.int[1]
  ucl <- tst$conf.int[2]
  cov <- ( lcl <= PopDiff & PopDiff <= ucl )
  stat <- c(TrueDif = PopDiff, dif = dif, lcl = lcl, ucl=ucl, Cover = cov ) 
  tmpout <- rbind(tmpout, stat  )
}
head(tmpout)
print(apply(tmpout, 2, mean))

}
```
     
```{r}
# Set seed
set.seed(100)

# N = 100
B = 10000

## Step 1: Compute population parameter for true difference between means:
#
# Population-level mean difference, PopDiff
PopDiff <-  -diff(t.test(kcal ~ female, data=HwkPop)$estimate )

## Step 2: Generate random samples of size N for your Monte Carlo simulation
#          Place random samples in a list of data frames (make's life easier):

N <- c(40, 60, 80, 100,)
for (i in 1:length(N)) {
  
data_list <- map(.x = 1:B, .f = ~ sample_n(HwkPop, N[i]))
head(data_list[[1]])

## Step: 3: Collect your MC estimates and safe them in tmpout.
#           In this illustration, We've saved:
#           dif  = estimated mean difference: mean(Y[X==0]) - mean(Y[X==1])
#           lcl  = lower 95% conf. inv. estimate
#           ucl  = upper 95% conf. inv. estimate
#           cov  = decision of whether the CI contains the true difference
#           TrueDif = Population mean difference 

tmpout <- NULL
for(i in 1:B) {
#  tmpout <- rbind(tmpout, ( prod( t.test( kcal ~  female, data=data_list[[i]])$conf.int - TrueDif) < 0 )  )
  tst <- t.test( kcal ~  female, data=data_list[[i]])
  dif <- -diff(tst$estimate)
  lcl <- tst$conf.int[1]
  ucl <- tst$conf.int[2]
  cov <- ( lcl <= PopDiff & PopDiff <= ucl )
  stat <- c(TrueDif = PopDiff, dif = dif, lcl = lcl, ucl=ucl, Cover = cov ) 
  tmpout <- rbind(tmpout, stat  )
}
head(tmpout)
print(apply(tmpout, 2, mean))

}
```

        